name: hymnes_sda_fr
description: "An app for French Seventh-day Adventist hymns with audio playback, lyrics display, and music sheet viewing capabilities."
publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  # sentry
  sentry_flutter: ^9.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  # Navigation
  go_router: ^12.1.3
  # State management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Settings storage
  shared_preferences: ^2.2.2
  # Icon generator
  flutter_launcher_icons: ^0.13.1
  # Local storage
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  # Spacing widget
  gap: ^3.0.1
  # Audio playback
  just_audio: ^0.9.36
  # Web view for PDF display
  webview_flutter: ^4.10.0
  http: ^1.1.0
  url_launcher: ^6.2.2
  # For firebase authentication
  firebase_auth: ^6.1.0
  # For firebase core
  firebase_core: ^4.1.1
  # For Google Sign-In
  google_sign_in: ^6.2.0
  # For Apple Sign-In
  sign_in_with_apple: ^6.1.0
  # For logging
  logger: ^2.3.0
  # For getting app version info
  package_info_plus: ^4.2.0
  # For file system access
  path_provider: ^2.1.2
  # For shimmer loading effects
  shimmer: ^3.0.0
  # Firestore database cloud_firestore
  cloud_firestore: ^6.0.2
  # posthog analytics
  posthog_flutter: ^5.0.0
  # tutorial coach mark
  tutorial_coach_mark: ^1.3.1
  # App update checker
  upgrader: ^12.1.0
  # Local notifications
  flutter_local_notifications: ^17.2.3
  # Permission handler for notification permissions
  permission_handler: ^11.3.1
  # Timezone support for scheduled notifications
  timezone: ^0.9.4
  # OneSignal for push notifications
  onesignal_flutter: ^5.3.4

dev_dependencies:
  # sentry
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  objectbox_generator: ^5.0.0
  build_runner: ^2.4.7
  flutter_gen: ^5.12.0
  # Testing dependencies
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/data/
    - shorebird.yaml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter_gen:
  output: lib/gen/
  # line_length: 80

# sentry
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: joemdjossou
