// Mocks generated by Mockito 5.4.5 from annotations
// in hymnes_sda_fr/test/unit/blocs/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hymnes_sda_fr/core/models/hymn.dart' as _i5;
import 'package:hymnes_sda_fr/core/repositories/i_hymn_repository.dart' as _i2;
import 'package:hymnes_sda_fr/features/favorites/models/favorite_hymn.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IFavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFavoriteRepository extends _i1.Mock
    implements _i2.IFavoriteRepository {
  MockIFavoriteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FavoriteHymn>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.FavoriteHymn>>.value(<_i4.FavoriteHymn>[]),
      ) as _i3.Future<List<_i4.FavoriteHymn>>);

  @override
  _i3.Future<List<_i5.Hymn>> getFavoritesAsHymns() => (super.noSuchMethod(
        Invocation.method(
          #getFavoritesAsHymns,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Hymn>>.value(<_i5.Hymn>[]),
      ) as _i3.Future<List<_i5.Hymn>>);

  @override
  _i3.Future<void> addToFavorites(_i5.Hymn? hymn) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [hymn],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromFavorites(String? hymnNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [hymnNumber],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool isFavorite(String? hymnNumber) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [hymnNumber],
        ),
        returnValue: false,
      ) as bool);
}
